<?php require_once 'parts/header.phtml'; ?>

<div class="mt-3 container">
    <form action="/save" method="POST">
        <div class="mb-3">
            <label for="firstname" class="form-label">First Name</label>
            <input type="text" class="form-control" name="firstname" id="firstname" />
        </div>
        <div class="mb-3">
            <label for="lastname" class="form-label">Last Name</label>
            <input type="text" class="form-control" name="firstname" id="firstname" />
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
<?php require_once 'parts/footer.phtml'; ?>
