<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PHP CRUD</title>
</head>
<body>
    <form action="/create" method="POST">
        <label for="message">Message</label>
        <input type="text" name="message" id="message"/>
        <button type="submit">Create</button>
    </form>
</body>
</html>
